name: "Sphinx: Render and Deploy Docs"

on:
  push:
    branches:
      - main  # Trigger on pushes to the default branch
  pull_request:
    paths:
      - 'docs/**'  # Only trigger for changes in the docs folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for GitHub Pages deployment
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Adjust to your project's version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt || echo "No additional dependencies"

      # Step 4: Build Sphinx documentation
      - name: Build HTML documentation
        run: sphinx-build -b html docs/ docs/_build/html

      # Step 5 (Optional): Upload artifacts for debugging
      - name: Upload artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html  
          cname: "kbabuji.com"  
